# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT License, Copyright 2022 MRH0"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/mrh0/createaddition/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="createaddition" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Create Crafts & Additions" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/mrh0/createaddition" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="createaddition.png" #optional
# A text field displayed in the mod UI
credits="Special Thanks to the Forge Discord and the Create Team." #optional
# A text field displayed in the mod UI
authors="MRH0" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Create Crafts & Additions extends Create and acts as a bridge between electric and kinetic energy from Create.
Join the Discord: https://discord.gg/mRbNnyKTEu
Special thanks to:
the Create team, the Forge team, and all contributors on the CC&A discord including: 
AlphaMode, BobDole, legoatoom, StockiesLad, THEREDSTONEBRO, and Uraxys.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.createaddition]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.createaddition]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.b,0.5.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createaddition]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.8.a,0.7)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.createaddition]]
    modId="immersiveengineering"
    mandatory=false
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createaddition]]
    modId="computercraft"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createaddition]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
